language: node_js
sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  matrix:
  - NODE_VER=4 FULL_VALIDATE=false
  - NODE_VER=5 FULL_VALIDATE=false
  - NODE_VER=6 FULL_VALIDATE=false
  - NODE_VER=7 FULL_VALIDATE=false
  - NODE_VER=8 FULL_VALIDATE=true

matrix:
  fast_finish: true

before_install:
  - nvm install $NODE_VER
  - npm install -g npm@5.4.1
  - npm install -g greenkeeper-lockfile@1
  - node -v && npm -v

install:
  - npm install
  - if [ "$FULL_VALIDATE" == "true" ]; then npm run lint; fi

before_script: greenkeeper-lockfile-update

script:
  - npm run build
  - npm test

after_script: greenkeeper-lockfile-upload

after_success:
#limiting coverage under spec/hunspell-asm test to avoid wasm integration test results are being collected.
  - if [ "$FULL_VALIDATE" == "true" ]; then npm run test:hunspell-asm && bash <(curl -s https://codecov.io/bash); fi