environment:
  matrix:
    - nodejs_version: "10"

install:
  - cinst wget
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install -g npm@latest
  - node -v && npm -v
  - npm install

build_script:
  - npm run build

test_script:
  - npm test

version: "{build}"